/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.djiordhan.generator;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;

/**
 *
 * @author user
 */
public class Main extends javax.swing.JFrame {

    private JFileChooser fileChooser;
    private File file;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        fileChooser = new JFileChooser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFilePath = new javax.swing.JTextField();
        btnFileChooser = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        scrollDataSource = new javax.swing.JScrollPane();
        txtDataSource = new javax.swing.JTextArea();
        scrollUsage = new javax.swing.JScrollPane();
        txtUsage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFileChooser.setText("Browse");
        btnFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileChooserActionPerformed(evt);
            }
        });

        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        txtDataSource.setColumns(20);
        txtDataSource.setRows(5);
        scrollDataSource.setViewportView(txtDataSource);

        txtUsage.setColumns(20);
        txtUsage.setRows(5);
        scrollUsage.setViewportView(txtUsage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollDataSource, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFilePath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFileChooser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerate))
                    .addComponent(scrollUsage))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFileChooser)
                    .addComponent(btnGenerate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollDataSource, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollUsage, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileChooserActionPerformed
        // TODO add your handling code here:
        int i = fileChooser.showOpenDialog(null);
        if (i == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
            txtFilePath.setText(file.getPath());
        }
    }//GEN-LAST:event_btnFileChooserActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        boolean fieldNamePassed = false;
        int NumOffieldNamePassed = 0;
        int counter = 0;
        if (file != null && file.exists()) {

            String fileName = file.getName().replace(".jrxml", "") + "DataSource";

            List<String> fieldNames = new ArrayList();

            try {
                BufferedReader br = new BufferedReader(new FileReader(file));
                String n;
                while ((n = br.readLine()) != null) {
                    counter++;
                    if (n.contains("<field ")) {

                        fieldNamePassed = true;
                        if (fieldNamePassed) {
                            NumOffieldNamePassed++;
                        }

                        int from = n.indexOf("\"") + 1;
                        int to = n.indexOf("\"", from);

                        String fieldName = n.substring(from, to);
                        fieldNames.add(fieldName);

                    } else {
                        if (fieldNamePassed && ((counter - NumOffieldNamePassed) > 10)) {
                            System.out.println("End: " + counter + "!");
                            break;
                        }
                    }
                }

                String dataSource = generateDataSource(fileName, fieldNames);
                String dataSourceInstance = generateDataSourceInstance(fileName, fieldNames);
                generateDataSourceText(fileName, fieldNames);
                generateDataSourceInstanceText(fileName, fieldNames);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnGenerateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFileChooser;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JScrollPane scrollDataSource;
    private javax.swing.JScrollPane scrollUsage;
    private javax.swing.JTextArea txtDataSource;
    private javax.swing.JTextField txtFilePath;
    private javax.swing.JTextArea txtUsage;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the fileChooser
     */
    public JFileChooser getjFileChooser() {
        return fileChooser;
    }

    /**
     * @param jFileChooser the fileChooser to set
     */
    public void setjFileChooser(JFileChooser jFileChooser) {
        this.fileChooser = jFileChooser;
    }

    /**
     * @return the file
     */
    public File getFile() {
        return file;
    }

    /**
     * @param file the file to set
     */
    public void setFile(File file) {
        this.file = file;
    }

    public String generateDataSource(String className, List<String> fieldNames) {
        String generated = ""
                + "import net.sf.jasperreports.engine.JRDataSource;"
                + "import net.sf.jasperreports.engine.JRException;"
                + "import net.sf.jasperreports.engine.JRField;"
                + "public class " + className + " implements JRDataSource {";

        //Field Names
        generated = fieldNames.stream().map((f) -> "private String " + f + ";").reduce(generated, String::concat);
        //read
        generated += "int read = 0;";
        //next
        generated += "@Override public boolean next() throws JRException { read++; return read != 2; }";
        //constructor
        generated += "public " + className + "(){}";

        //getfieldvalue
        generated += "@Override public Object getFieldValue(JRField jrf) throws JRException { String fieldName = jrf.getName();";

        boolean first = true;
        for (String f : fieldNames) {

            if (first) {
                generated += "if (fieldName.equals(\"" + f + "\")) { return " + f + "; }";
            } else {
                generated += "else if (fieldName.equals(\"" + f + "\")) { return " + f + "; }";
            }

            first = false;
        }

        generated += " return null; }";

        //encapsulation
        for (String f : fieldNames) {
            generated += "public String get" + f.replaceFirst(f.charAt(0) + "", (f.charAt(0) + "").toUpperCase()) + "(){ return this." + f + "; }";
            generated += "public void set" + f.replaceFirst(f.charAt(0) + "", (f.charAt(0) + "").toUpperCase()) + "(String " + f + "){ this." + f + " = " + f + "; }";
        }

        generated += "}";
        return generated;
    }

    public String generateDataSourceInstance(String className, List<String> fieldNames) {
        String generated = "";

        generated += className + " dataSource = new " + className + "();";
        generated = fieldNames.stream().map((f) -> "dataSource.set" + f.replaceFirst(f.charAt(0) + "", (f.charAt(0) + "").toUpperCase()) + "(\"" + f + "\");").reduce(generated, String::concat);

        return generated;
    }

    public String generateDataSourceText(String className, List<String> fieldNames) {
        String generated = "";

        txtDataSource.append("import net.sf.jasperreports.engine.JRDataSource;\n");
        txtDataSource.append("import net.sf.jasperreports.engine.JRException;\n");
        txtDataSource.append("import net.sf.jasperreports.engine.JRField;\n\n");
        txtDataSource.append("public class " + className + " implements JRDataSource {\n\n");
        //Field Names
        fieldNames.stream().forEach((f) -> {
            txtDataSource.append("private String " + f + ";\n");
        });
        //read
        txtDataSource.append("int read = 0;\n\n");
        //next
        txtDataSource.append("@Override\n public boolean next() throws JRException {\n read++;\n return read != 2;\n }\n");
        //constructor
        txtDataSource.append("public " + className + "(){\n}\n");
        //getfieldvalue
        txtDataSource.append("@Override\n public Object getFieldValue(JRField jrf) throws JRException {\n String fieldName = jrf.getName();\n");

        boolean first = true;
        for (String f : fieldNames) {

            if (first) {
                txtDataSource.append("if (fieldName.equals(\"" + f + "\")) {\n return " + f + ";\n }\n");
            } else {
                txtDataSource.append("else if (fieldName.equals(\"" + f + "\")) {\n return " + f + ";\n }\n");
            }

            first = false;
        }

        txtDataSource.append(" return null;\n }\n");
        //encapsulation
        for (String f : fieldNames) {
            txtDataSource.append("public String get" + f.replaceFirst(f.charAt(0) + "", (f.charAt(0) + "").toUpperCase()) + "(){\n return this." + f + ";\n }\n");
            txtDataSource.append("public void set" + f.replaceFirst(f.charAt(0) + "", (f.charAt(0) + "").toUpperCase()) + "(String " + f + "){\n this." + f + " = " + f + ";\n }\n");
        }
        txtDataSource.append("}\n");
        return generated;
    }

    public String generateDataSourceInstanceText(String className, List<String> fieldNames) {
        String generated = "";
        txtUsage.append(className + " dataSource = new " + className + "();\n");
        fieldNames.stream().forEach((f) -> {
            txtUsage.append("dataSource.set" + f.replaceFirst(f.charAt(0) + "", (f.charAt(0) + "").toUpperCase()) + "(\"" + f + "\");\n");
        });
        return generated;
    }
}
